# Generated by Django 4.2.1 on 2023-05-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('track', models.CharField(default='', max_length=50)),
                ('road', models.CharField(default='', max_length=50)),
                ('xc', models.CharField(default='', max_length=50)),
                ('sex', models.CharField(default='', max_length=50)),
                ('club', models.CharField(default='', max_length=50)),
                ('athlete_id', models.IntegerField()),
                ('gender', models.CharField(default='', max_length=5)),
                ('age_group', models.CharField(default='', max_length=50)),
                ('county', models.CharField(default='', max_length=50)),
                ('region', models.CharField(default='', max_length=50)),
                ('nation', models.CharField(default='', max_length=50)),
                ('lead_coach', models.CharField(default='', max_length=50)),
                ('about', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='', max_length=50)),
                ('age_group', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataload.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='performances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='', max_length=50)),
                ('value', models.CharField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('raceid', models.CharField(default='', max_length=50)),
                ('venue', models.CharField(default='', max_length=50)),
                ('meeting', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataload.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='pbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='', max_length=50)),
                ('value', models.FloatField(null=True)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataload.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='coaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('club', models.CharField(default='', max_length=50)),
                ('age_group', models.CharField(default='', max_length=50)),
                ('sex', models.CharField(default='', max_length=50)),
                ('best_event', models.CharField(default='', max_length=50)),
                ('rank', models.IntegerField()),
                ('age_group_rank', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField()),
                ('performance', models.FloatField(null=True)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataload.athlete')),
            ],
        ),
    ]
