# Generated by Django 4.2.1 on 2023-05-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performances',
            name='value',
            field=models.FloatField(default='', max_length=50),
        ),
    ]
