# Generated by Django 4.2.1 on 2023-05-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0002_alter_performances_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbs',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='performances',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
