# Generated by Django 4.2.1 on 2023-05-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0003_alter_pbs_value_alter_performances_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='about',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='county',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='lead_coach',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='region',
        ),
    ]
