# Generated by Django 4.2.1 on 2023-05-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0004_remove_athlete_about_remove_athlete_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='performance',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='rank',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='rank',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
    ]
