# Generated by Django 4.2.1 on 2023-05-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0005_alter_coaching_performance_alter_coaching_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performances',
            name='club_at_performance',
            field=models.CharField(default='', max_length=50),
        ),
    ]
