# Generated by Django 4.2.1 on 2023-05-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0006_performances_club_at_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performances',
            old_name='value',
            new_name='performance',
        ),
    ]
