# Generated by Django 4.2.1 on 2023-05-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0007_rename_value_performances_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
