# Generated by Django 4.2.1 on 2023-05-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0008_alter_athlete_athlete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='athlete_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pbs',
            name='athlete_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='performances',
            name='athlete_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='athlete_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
