# Generated by Django 4.2.1 on 2023-05-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0009_alter_coaching_athlete_id_alter_pbs_athlete_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performances',
            name='Age_Group_Performance',
            field=models.CharField(default='', max_length=50),
        ),
    ]
