# Generated by Django 4.2.1 on 2023-05-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0018_alter_meets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performances',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
