# Generated by Django 4.2.1 on 2023-06-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0023_results_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='performances',
            name='XCSeason',
            field=models.CharField(default='', max_length=50),
        ),
    ]
