# Generated by Django 3.2.19 on 2023-06-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataload', '0025_alter_performances_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performances',
            name='meeting',
            field=models.CharField(default='', max_length=300),
        ),
    ]
