# Generated by Django 4.2.1 on 2023-06-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dchcalendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
