# Generated by Django 4.2.1 on 2023-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchcalendar', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Test',
            field=models.TimeField(help_text='Test', null=True, verbose_name='Test'),
        ),
    ]
