# Generated by Django 4.2.1 on 2023-06-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchcalendar', '0004_event_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Test',
        ),
        migrations.AddField(
            model_name='event',
            name='Category',
            field=models.CharField(blank=True, choices=[('1', 'Championships'), ('2', 'League'), ('3', 'Training'), ('4', 'Other')], help_text='Event Type', max_length=32, null=True),
        ),
    ]
