# Generated by Django 4.2.1 on 2023-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchcalendar', '0006_event_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Age_Group',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Masters', 'Masters'), ('All', 'All')], help_text='Age Groups', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Category',
            field=models.CharField(blank=True, choices=[('Championships', 'Championships'), ('League', 'League'), ('Training', 'Training'), ('Other', 'Other')], help_text='Event Type', max_length=32, null=True),
        ),
    ]
